# Generated by Django 5.1.1 on 2024-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='descripcion',
            field=models.TextField(default='Descripcion No Proporcionada'),
            preserve_default=False,
        ),
    ]
